import { getValidAccessToken } from "@/lib/google-calendar.server";
import { getMessage, getAttachmentBytes } from "@/lib/gmail.server";
import { gmailMessageToRawItem } from "@/lib/gmail-discovery.server";
import { pickPrimaryCandidateAttachment } from "@/lib/candidate-attachment";
import { extractCvText } from "@/lib/cv-parse.server";
import { extractCvName, normalizeCvLines, personNameFrom } from "@/lib/cv-name";
const conn = (await getValidAccessToken(process.env.E2E_USER_ID!))!;
const msg = await getMessage(conn.access_token, "1a05c5633dfafd7e");
const raw = gmailMessageToRawItem(msg, null);
const p = pickPrimaryCandidateAttachment(raw.attachments)!;
const t = await extractCvText(await getAttachmentBytes(conn.access_token, msg.id, p.externalId), p.fileName, p.mimeType);
const lines = normalizeCvLines(t);
console.log(JSON.stringify(lines.slice(0, 12)));
console.log("personNameFrom line0:", personNameFrom(lines[0]!));
console.log("extractCvName:", extractCvName(t, p.fileName));
