/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as ScoutRouteImport } from './routes/scout'
import { Route as PositionsRouteImport } from './routes/positions'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as OngoingRouteImport } from './routes/ongoing'
import { Route as InterviewsRouteImport } from './routes/interviews'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ClosedRouteImport } from './routes/closed'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientIndexRouteImport } from './routes/client.index'
import { Route as PositionsPositionIdRouteImport } from './routes/positions.$positionId'
import { Route as ClientsClientIdRouteImport } from './routes/clients.$clientId'
import { Route as ClientUploadRouteImport } from './routes/client.upload'
import { Route as ClientPositionsRouteImport } from './routes/client.positions'
import { Route as ClientDocumentsRouteImport } from './routes/client.documents'
import { Route as AdminClientsRouteImport } from './routes/admin.clients'
import { Route as ClientPositionsPositionIdRouteImport } from './routes/client.positions.$positionId'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoutRoute = ScoutRouteImport.update({
  id: '/scout',
  path: '/scout',
  getParentRoute: () => rootRouteImport,
} as any)
const PositionsRoute = PositionsRouteImport.update({
  id: '/positions',
  path: '/positions',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const OngoingRoute = OngoingRouteImport.update({
  id: '/ongoing',
  path: '/ongoing',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewsRoute = InterviewsRouteImport.update({
  id: '/interviews',
  path: '/interviews',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ClosedRoute = ClosedRouteImport.update({
  id: '/closed',
  path: '/closed',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientIndexRoute = ClientIndexRouteImport.update({
  id: '/client/',
  path: '/client/',
  getParentRoute: () => rootRouteImport,
} as any)
const PositionsPositionIdRoute = PositionsPositionIdRouteImport.update({
  id: '/$positionId',
  path: '/$positionId',
  getParentRoute: () => PositionsRoute,
} as any)
const ClientsClientIdRoute = ClientsClientIdRouteImport.update({
  id: '/$clientId',
  path: '/$clientId',
  getParentRoute: () => ClientsRoute,
} as any)
const ClientUploadRoute = ClientUploadRouteImport.update({
  id: '/client/upload',
  path: '/client/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientPositionsRoute = ClientPositionsRouteImport.update({
  id: '/client/positions',
  path: '/client/positions',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientDocumentsRoute = ClientDocumentsRouteImport.update({
  id: '/client/documents',
  path: '/client/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminClientsRoute = AdminClientsRouteImport.update({
  id: '/admin/clients',
  path: '/admin/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientPositionsPositionIdRoute =
  ClientPositionsPositionIdRouteImport.update({
    id: '/$positionId',
    path: '/$positionId',
    getParentRoute: () => ClientPositionsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clients': typeof ClientsRouteWithChildren
  '/closed': typeof ClosedRoute
  '/dashboard': typeof DashboardRoute
  '/interviews': typeof InterviewsRoute
  '/ongoing': typeof OngoingRoute
  '/pipeline': typeof PipelineRoute
  '/positions': typeof PositionsRouteWithChildren
  '/scout': typeof ScoutRoute
  '/tasks': typeof TasksRoute
  '/team': typeof TeamRoute
  '/admin/clients': typeof AdminClientsRoute
  '/client/documents': typeof ClientDocumentsRoute
  '/client/positions': typeof ClientPositionsRouteWithChildren
  '/client/upload': typeof ClientUploadRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/positions/$positionId': typeof PositionsPositionIdRoute
  '/client/': typeof ClientIndexRoute
  '/client/positions/$positionId': typeof ClientPositionsPositionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clients': typeof ClientsRouteWithChildren
  '/closed': typeof ClosedRoute
  '/dashboard': typeof DashboardRoute
  '/interviews': typeof InterviewsRoute
  '/ongoing': typeof OngoingRoute
  '/pipeline': typeof PipelineRoute
  '/positions': typeof PositionsRouteWithChildren
  '/scout': typeof ScoutRoute
  '/tasks': typeof TasksRoute
  '/team': typeof TeamRoute
  '/admin/clients': typeof AdminClientsRoute
  '/client/documents': typeof ClientDocumentsRoute
  '/client/positions': typeof ClientPositionsRouteWithChildren
  '/client/upload': typeof ClientUploadRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/positions/$positionId': typeof PositionsPositionIdRoute
  '/client': typeof ClientIndexRoute
  '/client/positions/$positionId': typeof ClientPositionsPositionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clients': typeof ClientsRouteWithChildren
  '/closed': typeof ClosedRoute
  '/dashboard': typeof DashboardRoute
  '/interviews': typeof InterviewsRoute
  '/ongoing': typeof OngoingRoute
  '/pipeline': typeof PipelineRoute
  '/positions': typeof PositionsRouteWithChildren
  '/scout': typeof ScoutRoute
  '/tasks': typeof TasksRoute
  '/team': typeof TeamRoute
  '/admin/clients': typeof AdminClientsRoute
  '/client/documents': typeof ClientDocumentsRoute
  '/client/positions': typeof ClientPositionsRouteWithChildren
  '/client/upload': typeof ClientUploadRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/positions/$positionId': typeof PositionsPositionIdRoute
  '/client/': typeof ClientIndexRoute
  '/client/positions/$positionId': typeof ClientPositionsPositionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clients'
    | '/closed'
    | '/dashboard'
    | '/interviews'
    | '/ongoing'
    | '/pipeline'
    | '/positions'
    | '/scout'
    | '/tasks'
    | '/team'
    | '/admin/clients'
    | '/client/documents'
    | '/client/positions'
    | '/client/upload'
    | '/clients/$clientId'
    | '/positions/$positionId'
    | '/client/'
    | '/client/positions/$positionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clients'
    | '/closed'
    | '/dashboard'
    | '/interviews'
    | '/ongoing'
    | '/pipeline'
    | '/positions'
    | '/scout'
    | '/tasks'
    | '/team'
    | '/admin/clients'
    | '/client/documents'
    | '/client/positions'
    | '/client/upload'
    | '/clients/$clientId'
    | '/positions/$positionId'
    | '/client'
    | '/client/positions/$positionId'
  id:
    | '__root__'
    | '/'
    | '/clients'
    | '/closed'
    | '/dashboard'
    | '/interviews'
    | '/ongoing'
    | '/pipeline'
    | '/positions'
    | '/scout'
    | '/tasks'
    | '/team'
    | '/admin/clients'
    | '/client/documents'
    | '/client/positions'
    | '/client/upload'
    | '/clients/$clientId'
    | '/positions/$positionId'
    | '/client/'
    | '/client/positions/$positionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientsRoute: typeof ClientsRouteWithChildren
  ClosedRoute: typeof ClosedRoute
  DashboardRoute: typeof DashboardRoute
  InterviewsRoute: typeof InterviewsRoute
  OngoingRoute: typeof OngoingRoute
  PipelineRoute: typeof PipelineRoute
  PositionsRoute: typeof PositionsRouteWithChildren
  ScoutRoute: typeof ScoutRoute
  TasksRoute: typeof TasksRoute
  TeamRoute: typeof TeamRoute
  AdminClientsRoute: typeof AdminClientsRoute
  ClientDocumentsRoute: typeof ClientDocumentsRoute
  ClientPositionsRoute: typeof ClientPositionsRouteWithChildren
  ClientUploadRoute: typeof ClientUploadRoute
  ClientIndexRoute: typeof ClientIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scout': {
      id: '/scout'
      path: '/scout'
      fullPath: '/scout'
      preLoaderRoute: typeof ScoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/positions': {
      id: '/positions'
      path: '/positions'
      fullPath: '/positions'
      preLoaderRoute: typeof PositionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ongoing': {
      id: '/ongoing'
      path: '/ongoing'
      fullPath: '/ongoing'
      preLoaderRoute: typeof OngoingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interviews': {
      id: '/interviews'
      path: '/interviews'
      fullPath: '/interviews'
      preLoaderRoute: typeof InterviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/closed': {
      id: '/closed'
      path: '/closed'
      fullPath: '/closed'
      preLoaderRoute: typeof ClosedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/': {
      id: '/client/'
      path: '/client'
      fullPath: '/client/'
      preLoaderRoute: typeof ClientIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/positions/$positionId': {
      id: '/positions/$positionId'
      path: '/$positionId'
      fullPath: '/positions/$positionId'
      preLoaderRoute: typeof PositionsPositionIdRouteImport
      parentRoute: typeof PositionsRoute
    }
    '/clients/$clientId': {
      id: '/clients/$clientId'
      path: '/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof ClientsClientIdRouteImport
      parentRoute: typeof ClientsRoute
    }
    '/client/upload': {
      id: '/client/upload'
      path: '/client/upload'
      fullPath: '/client/upload'
      preLoaderRoute: typeof ClientUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/positions': {
      id: '/client/positions'
      path: '/client/positions'
      fullPath: '/client/positions'
      preLoaderRoute: typeof ClientPositionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/documents': {
      id: '/client/documents'
      path: '/client/documents'
      fullPath: '/client/documents'
      preLoaderRoute: typeof ClientDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/clients': {
      id: '/admin/clients'
      path: '/admin/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AdminClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/positions/$positionId': {
      id: '/client/positions/$positionId'
      path: '/$positionId'
      fullPath: '/client/positions/$positionId'
      preLoaderRoute: typeof ClientPositionsPositionIdRouteImport
      parentRoute: typeof ClientPositionsRoute
    }
  }
}

interface ClientsRouteChildren {
  ClientsClientIdRoute: typeof ClientsClientIdRoute
}

const ClientsRouteChildren: ClientsRouteChildren = {
  ClientsClientIdRoute: ClientsClientIdRoute,
}

const ClientsRouteWithChildren =
  ClientsRoute._addFileChildren(ClientsRouteChildren)

interface PositionsRouteChildren {
  PositionsPositionIdRoute: typeof PositionsPositionIdRoute
}

const PositionsRouteChildren: PositionsRouteChildren = {
  PositionsPositionIdRoute: PositionsPositionIdRoute,
}

const PositionsRouteWithChildren = PositionsRoute._addFileChildren(
  PositionsRouteChildren,
)

interface ClientPositionsRouteChildren {
  ClientPositionsPositionIdRoute: typeof ClientPositionsPositionIdRoute
}

const ClientPositionsRouteChildren: ClientPositionsRouteChildren = {
  ClientPositionsPositionIdRoute: ClientPositionsPositionIdRoute,
}

const ClientPositionsRouteWithChildren = ClientPositionsRoute._addFileChildren(
  ClientPositionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientsRoute: ClientsRouteWithChildren,
  ClosedRoute: ClosedRoute,
  DashboardRoute: DashboardRoute,
  InterviewsRoute: InterviewsRoute,
  OngoingRoute: OngoingRoute,
  PipelineRoute: PipelineRoute,
  PositionsRoute: PositionsRouteWithChildren,
  ScoutRoute: ScoutRoute,
  TasksRoute: TasksRoute,
  TeamRoute: TeamRoute,
  AdminClientsRoute: AdminClientsRoute,
  ClientDocumentsRoute: ClientDocumentsRoute,
  ClientPositionsRoute: ClientPositionsRouteWithChildren,
  ClientUploadRoute: ClientUploadRoute,
  ClientIndexRoute: ClientIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
