
-- Wipe all app/domain data while preserving auth.users, profiles, user_roles, role_permissions.
TRUNCATE TABLE
  public.activities,
  public.messages,
  public.message_threads,
  public.notifications,
  public.notification_dedup,
  public.tasks,
  public.support_tickets,
  public.invoice_line_items,
  public.invoices,
  public.client_billing_terms,
  public.placements,
  public.interviews,
  public.applications,
  public.job_applications,
  public.job_post_channels,
  public.job_posts,
  public.position_sourced_matches,
  public.position_sourcing_runs,
  public.sourced_candidates,
  public.candidates,
  public.positions,
  public.client_role_permissions,
  public.client_custom_roles,
  public.client_members,
  public.clients,
  public.interview_round_templates,
  public.scout_source_settings,
  public.google_calendar_connections,
  public.recruiter_login_events,
  public.agency_members,
  public.agencies,
  public.documents
RESTART IDENTITY CASCADE;
