DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_enum WHERE enumlabel = 'lead_recruiter' AND enumtypid = 'public.app_role'::regtype) THEN ALTER TYPE public.app_role ADD VALUE 'lead_recruiter'; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_enum WHERE enumlabel = 'recruiter' AND enumtypid = 'public.app_role'::regtype) THEN ALTER TYPE public.app_role ADD VALUE 'recruiter'; END IF; END $$;
DO $$ BEGIN CREATE TYPE public.position_priority AS ENUM ('high','medium','low'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public.position_status AS ENUM ('open','in_progress','interviews','closed'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public.client_status AS ENUM ('active','inactive'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE TABLE IF NOT EXISTS public.clients (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name TEXT NOT NULL, industry TEXT, contact_name TEXT, contact_email TEXT, contact_phone TEXT, status public.client_status NOT NULL DEFAULT 'active', notes TEXT, color TEXT, last_activity_at TIMESTAMPTZ, created_by UUID, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
ALTER TABLE public.clients ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Staff can view clients" ON public.clients FOR SELECT TO authenticated USING (public.has_role(auth.uid(),'admin') OR public.has_role(auth.uid(),'lead_recruiter') OR public.has_role(auth.uid(),'recruiter'));
CREATE POLICY "Admins leads insert clients" ON public.clients FOR INSERT TO authenticated WITH CHECK (public.has_role(auth.uid(),'admin') OR public.has_role(auth.uid(),'lead_recruiter'));
CREATE POLICY "Admins leads update clients" ON public.clients FOR UPDATE TO authenticated USING (public.has_role(auth.uid(),'admin') OR public.has_role(auth.uid(),'lead_recruiter'));
CREATE POLICY "Admins leads delete clients" ON public.clients FOR DELETE TO authenticated USING (public.has_role(auth.uid(),'admin') OR public.has_role(auth.uid(),'lead_recruiter'));
CREATE TRIGGER trg_clients_updated_at BEFORE UPDATE ON public.clients FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TABLE IF NOT EXISTS public.positions (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), client_id UUID NOT NULL REFERENCES public.clients(id) ON DELETE CASCADE, title TEXT NOT NULL, location TEXT, experience TEXT, salary TEXT, openings INTEGER NOT NULL DEFAULT 1, priority public.position_priority NOT NULL DEFAULT 'medium', status public.position_status NOT NULL DEFAULT 'open', description TEXT, skills TEXT[] NOT NULL DEFAULT '{}', posted_at TIMESTAMPTZ NOT NULL DEFAULT now(), created_by UUID, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_positions_client_id ON public.positions(client_id);
CREATE INDEX IF NOT EXISTS idx_positions_status ON public.positions(status);
ALTER TABLE public.positions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Staff view positions" ON public.positions FOR SELECT TO authenticated USING (public.has_role(auth.uid(),'admin') OR public.has_role(auth.uid(),'lead_recruiter') OR public.has_role(auth.uid(),'recruiter'));
CREATE POLICY "Staff insert positions" ON public.positions FOR INSERT TO authenticated WITH CHECK (public.has_role(auth.uid(),'admin') OR public.has_role(auth.uid(),'lead_recruiter') OR public.has_role(auth.uid(),'recruiter'));
CREATE POLICY "Staff update positions" ON public.positions FOR UPDATE TO authenticated USING (public.has_role(auth.uid(),'admin') OR public.has_role(auth.uid(),'lead_recruiter') OR public.has_role(auth.uid(),'recruiter'));
CREATE POLICY "Admins leads delete positions" ON public.positions FOR DELETE TO authenticated USING (public.has_role(auth.uid(),'admin') OR public.has_role(auth.uid(),'lead_recruiter'));
CREATE TRIGGER trg_positions_updated_at BEFORE UPDATE ON public.positions FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();